name: Basic test

on: push

jobs:
  build:
    name: Run test
    runs-on: ubuntu-latest

    steps: 
      - name: checkout repo content
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: add PYTHONPATH
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src/" >> $GITHUB_PATH && echo "PYTHONPATH=${GITHUB_WORKSPACE}/src/test_utils" >> $GITHUB_PATH
      - name: add PYTHONPATH 2
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src/test_utils" >> $GITHUB_PATH
      - name: add PYTHONPATH 3
        run: echo "PYTHONPATH=${GITHUB_WORKSPACE}/src" >> $GITHUB_PATH    
      - name: print GITHUB_PATH
        run: echo $GITHUB_PATH
      - run: python src/tests/run_test.py
